name: Release Go Module

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to Go Module Proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Index module version
        env:
          VERSION: ${{ github.ref_name }}
        run: GOPROXY=https://proxy.golang.org go list -m langdag.com/langdag@$VERSION
